import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';
import Product from '../components/Product';
import styles from '../styles/Home.module.css';

export default function Home({ products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title> e - commerece </title>{' '}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid items-center grid-cols-1 py-5 mt-5 text-center md:grid-cols-2 xl:grid-cols-3">
        {products.map((product) => (
          <Product key={product.id} product={product} />
        ))}
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />{' '}
          </span>{' '}
        </a>{' '}
      </footer>{' '}
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch('https://fakestoreapi.com/products');
  const products = await res.json();
  return {
    props: {
      products,
    },
  };
}
